@URL = http://localhost/CC3DeCria/api

GET {{URL}}/compra/get.php

###Criar compra
POST {{URL}}/compra/create.php
Content-Type: application/json

{
    "id_usuario": 4,
    "valor": 2,
    "data_compra": "2023-10-22",
    "itens": [
        {
            "produto_id": 1,
            "quantidade": 2
        },
        {
            "produto_id": 2,
            "quantidade": 1
        }
    ]
}

### Atualizar compra
POST {{URL}}/compra/update.php?id_compra=1
Content-Type: application/json

{
    "valor": 111,
    "data_compra": "2023-10-22"
}

###Deletar compra
GET {{URL}}/compra/delete.php?id_compra=1

